spring:
  application:
    name: eureka-client-ribbon-hystrix
server:
  port: 8777

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
